#!/bin/sh


# Check if .gitattributes exists (windows line endings)
if [ ! -f .gitattributes ]; then
    cat <<EOF > .gitattributes
* text=auto eol=lf
*.{cmd,[cC][mM][dD]} text eol=crlf
*.{bat,[bB][aA][tT]} text eol=crlf
EOF
    exit 1
fi

# Check if .gitignore exists
if [ ! -f .gitignore ]; then
    cat <<EOF > .gitignore
# Go find a good starter .gitignore file at
# https://github.com/github/gitignore
# Best case, keep it as short as possible.
# IMPORTANT: Use this to keep your .env file out of git
# Ignore everything
*
# Except gitignore
!.gitignore
EOF
    exit 1
fi

# run local pre-commit hook if it exists
repo_hook=".git/hooks/pre-commit"
if [ -x "$repo_hook" ]; then
    exec "$repo_hook"
else
    echo "No repository-level pre-commit hook found. Continuing with system-level actions..."
fi
