#!/usr/bin/env zsh
# set gitenv
#echo "Initialize gitenv"

gitenv() {
    if hash git 2>/dev/null; then
      envsubst < ${XDG_CONFIG_HOME}/git/config_template > ${XDG_CONFIG_HOME}/git/config
    else
      echo "Please install git"
    fi
    if hash gh 2>/dev/null; then
      gh auth status
      if [ $? -eq 0 ]; then
        mkdir -p ${XDG_CONFIG_HOME}/git
        cat <<EOF >>${XDG_CONFIG_HOME}/git/config
[user]
  name = $(gh api user --jq '.name')
  email = $(gh api user --jq '(.id | tostring) + "+" + .login + "@users.noreply.github.com"')
[alias]
  initFull = !sh ${XDG_CONFIG_HOME}/git/scripts/initFull.sh
  amend = commiti -a --amend -C HEAD
  contains = branch --contains
  hist = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --branches
EOF
      else
        echo "There's a problem connecting to gh cli"
      fi
    else
      echo "Please install gh cli"
    fi
}
# end set gitenv
