#!/usr/bin/env zsh
# setup for tmux


tmuxsetup() {
    if command -v tmux &> /dev/null; then
      if [[ ! -d ${XDG_CACHE_HOME}/tmux/plugins ]]; then
        mkdir -p ${XDG_CACHE_HOME}/tmux/plugins
        git clone https://github.com/tmux-plugins/tpm ${XDG_CACHE_HOME}/tmux/plugins/tpm
      else
        echo "if having issues with tmux, rm -rf ~/.cache/tmux and restart terminal"
      fi
    fi
}
